miPrimerApp/miPrimerApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls"))
]

miPrimerApp/polls/urls.py
from django.urls import path
from . import views
#rutas de la app polls

app_name = "polls"

urlpatterns = [
    #example: /polls
    path("", views.IndexView.as_view(), name="index"),
    #example: /polls/5/
    path("<int:pk>/details", views.DetailsView.as_view(), name="details"),
    #example: /polls/5/results/
    path("<int:pk>/results", views.ResultView.as_view(), name="results"),
    #example: /polls/5/votes/
    path("<int:question_id>/vote", views.vote, name="vote")
]

miPrimerApp/polls/models.py
from django.db import models
from django.utils import timezone #libreria de hora y fecha de django
import datetime #libreria de hora y fecha de python


#modelos o clases del ORM
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published" ,auto_now_add=True)
    #auto_now_add=True pone la fecha y hora automaticamente al crear un registro
    
    #metodo str similar al toString de otros lenguaes de programación
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    #datetime.timedelta(days=1) 1 dia atrás apartir e la fecha actual
    #timezone.now() hora actual pero con zona horario django

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    #on_delete=models.CASCADE al elimar la Question se eliminan todas las respuestas asociadas
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    #metodo str similar al toString de otros lenguaes de programación
    def __str__(self):
        return self.choice

miPrimerApp/polls/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question, Choice
# Create your views here.
# estás visa esta hechas sin usar las generic views
# def index(request):
#     latest_question_list = Question.objects.all()
#     return render(request, "polls/index.html", {"latest_question_list":latest_question_list})

# def details(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/details.html", {"question": question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {
#         "question": question
#     })

#aca se usan las generic views

class IndexView(generic.ListView):
    context_object_name = "latest_question_list"
    template_name = "polls/index.html"
    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]

class DetailsView (generic.DetailView):
    model = Question
    template_name = "polls/details.html"

class ResultView (generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
        return render(request, "polls/details.html", {
            "question": question,
            "error_message": "No elegiste una respuesta"
        } )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

miPrimerApp/polls/templates/polls/details.html
{% comment %}
<h1>{{ question.question_text}}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>{{choice.choice}}</li>
  {% endfor %}
</ul>
{% endcomment %}

<form action="{% url 'polls:vote' question.id%}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
    {% endif %}
    {% for choice in question.choice_set.all %}
      <input 
        type="radio"
        name="choice"
        id="choice{{ forloop.counter}}"
        value={{choice.id}}
      >
      <label for="choice{{forloop.counter}}">
        {{choice.choice}}
      </label>
      <br>
    {% endfor %}
  </fieldset>
  <input type="submit" value="enviar">
</form>

miPrimerApp/polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}

  <li><a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available</p>
{% endif %}

miPrimerApp/polls/templates/polls/results.html
<h1>{{ question.question_text}}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{choice.choice}} -- {{ choice.votes }} vote{{ choice.votes | pluralize }}
  </li>
  {% endfor %}
</ul>
<a href="{% url 'polls:details' question.id %}">¿Te gustaria votar de nuevo?</a>